name: bruno cli CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_bruno_api_test:
    runs-on: ubuntu-latest
    environment: TEST
    steps:
    - uses: actions/checkout@v3
    - run: npm install
      env:
        APIKEY: ${{ secrets.APIKEY }}
    - run: echo ${{ secrets.APIKEY }}
    - name: run tests
      run: npm run bru-test -- --env-var apiKey="$APIKEY"